name: CONTINUOUS INTEGRATION

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  configurar_e_testar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8]
    steps:
      - uses: actions/checkout@v2
      - name: configurar JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: instalar dependências
        run: mvn clean install -DskipTests
      - name: checkstyle code - google
        run: mvn checkstyle:checkstyle
      - name: rodar testes e2e
        run: mvn clean test